const {catalog,regions,cars}=window.AUTO_DEAL_DATA;
const $=id=>document.getElementById(id);const brand=$("brand"),model=$("model"),region=$("region"),marketButton=$("marketSwitch");
Object.keys(catalog).forEach(value=>brand.add(new Option(value,value)));regions.forEach((value,index)=>region.add(new Option(value,index?value:"")));
brand.addEventListener("change",()=>{model.innerHTML='<option value="">Всі моделі</option>';const models=catalog[brand.value]||[];models.forEach(value=>model.add(new Option(value,value)));model.disabled=!models.length});
let onlyDeals=true;marketButton.addEventListener("click",()=>{onlyDeals=!onlyDeals;marketButton.querySelector(".switch").classList.toggle("active",onlyDeals);marketButton.setAttribute("aria-checked",String(onlyDeals))});
const numberValue=id=>$(id).value===""?null:Number($(id).value);
function searchCars(){const priceFrom=numberValue("priceFrom"),priceTo=numberValue("priceTo"),yearFrom=numberValue("yearFrom"),yearTo=numberValue("yearTo");if(priceFrom!==null&&priceTo!==null&&priceFrom>priceTo)return toast("Перевір діапазон ціни");if(yearFrom!==null&&yearTo!==null&&yearFrom>yearTo)return toast("Перевір діапазон років");const found=cars.filter(car=>(!brand.value||car.brand===brand.value)&&(!model.value||car.model===model.value)&&(priceFrom===null||car.price>=priceFrom)&&(priceTo===null||car.price<=priceTo)&&(yearFrom===null||car.year>=yearFrom)&&(yearTo===null||car.year<=yearTo)&&(!region.value||car.region===region.value)&&(!onlyDeals||car.price<=car.market*.85));render(found)}
function render(list){$("results").classList.add("show");$("count").textContent=`Знайдено: ${list.length}`;$("resultsList").innerHTML=list.length?list.map(car=>{const discount=Math.round((1-car.price/car.market)*100);return `<article class="car"><div class="car-photo-wrap"><img class="car-photo" src="${car.image}" alt="${car.brand} ${car.model}" loading="lazy"><span class="badge">−${discount}% ВІД РИНКУ</span><button class="save" data-save="${car.id}" aria-label="Зберегти">♡</button></div><div class="car-body"><div class="car-top"><div class="car-name">${car.brand} ${car.model}</div><div class="car-price">$${car.price.toLocaleString("en-US")}</div></div><div class="car-meta">${car.year} • ${car.fuel} • ${Math.round(car.mileage/1000)} тис. км</div><div class="market-price"><span>Ринок ≈ $${car.market.toLocaleString("en-US")}</span><span class="deal">↓ ${discount}%</span></div><div class="location">📍 ${car.region}</div><a class="car-link" href="${car.url}" data-demo="${car.url==="#"}">ВІДКРИТИ ОГОЛОШЕННЯ</a></div></article>`}).join(""):'<div class="empty">За цими фільтрами авто не знайдено.</div>';$("results").scrollIntoView({behavior:"smooth",block:"start"})}
function toast(message){const element=$("toast");element.textContent=message;element.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>element.classList.remove("show"),2200)}
$("searchBtn").addEventListener("click",searchCars);$("settingsBtn").addEventListener("click",()=>toast("Налаштування додамо наступним етапом"));$("resultsList").addEventListener("click",event=>{const save=event.target.closest("[data-save]");if(save){save.textContent=save.textContent==="♡"?"♥":"♡";toast(save.textContent==="♥"?"Авто збережено":"Авто видалено зі збережених")}const demo=event.target.closest('[data-demo="true"]');if(demo){event.preventDefault();toast("Посилання підключимо до реальних оголошень")}});document.querySelectorAll(".nav").forEach(item=>item.addEventListener("click",()=>{document.querySelectorAll(".nav").forEach(node=>node.classList.remove("active"));item.classList.add("active");if(item.dataset.tab!=="search")toast(`Розділ «${item.textContent.trim()}» — наступний етап`)}));
if(window.Telegram?.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand();}
