const assert=require("node:assert/strict");
const saved=require("./saved-searches.js");
let contents=null;
const storage={getItem:()=>contents,setItem:(key,value)=>{assert.equal(key,saved.KEY);contents=value;}};
const filters={brand:"BMW",model:"3 Series",region:"Київська область",price:{from:0,to:20000},year:{from:2018,to:null},mileage:{from:100,to:200},body:["Седан"],fuel:["Дизель","Бензин"],transmission:["Автомат"],onlyDeals:true};
assert.deepEqual(saved.read(storage),[]);
const item=saved.save(storage,filters,"BMW",true);
assert.equal(saved.read(storage)[0].notificationsWanted,true);
// Another read simulates reopening. Caller changes must not mutate snapshots.
filters.price.to=15000;
assert.equal(saved.read(storage)[0].filters.price.to,20000);
filters.price.to=20000;filters.fuel.reverse();
saved.save(storage,filters,"Новий підпис",false);
assert.equal(saved.read(storage).length,1);
assert.equal(saved.read(storage)[0].id,item.id);
assert.equal(saved.read(storage)[0].name,"Новий підпис");
saved.setWanted(storage,item.id,true);assert.equal(saved.read(storage)[0].notificationsWanted,true);
saved.remove(storage,item.id);assert.equal(saved.read(storage).length,0);
assert.throws(()=>saved.save(storage,{...filters,mileage:{from:200,to:100}},"bad",false));
assert.throws(()=>saved.save(storage,filters," ",false));
const quota={getItem:()=>null,setItem:()=>{throw Error("QuotaExceededError")}};
assert.throws(()=>saved.save(quota,filters,"BMW",true),/Quota/);
contents="{bad json";
assert.throws(()=>saved.save(storage,filters,"BMW",true));assert.equal(contents,"{bad json");
contents=JSON.stringify({version:99,searches:[]});
assert.throws(()=>saved.save(storage,filters,"BMW",true));assert.equal(JSON.parse(contents).version,99);
contents=null;
for(let i=0;i<20;i++)saved.save(storage,{...filters,price:{from:i,to:20000}},"Search "+i,false);
assert.throws(()=>saved.save(storage,{...filters,price:{from:21,to:20000}},"Extra",false),/20/);
assert.equal(saved.read(storage).length,20);
const first=saved.read(storage)[0],second=saved.read(storage)[1];
saved.update(storage,first.id,{...filters,price:{from:111,to:20000}},'Edited');
assert.equal(saved.read(storage).length,20);assert.equal(saved.read(storage)[0].id,first.id);
assert.equal(saved.read(storage)[0].filters.price.from,111);
const beforeConflict=contents;
assert.throws(()=>saved.update(storage,first.id,second.filters,'Duplicate'),/вже є/);
assert.throws(()=>saved.update(storage,'deleted',filters,'Missing'),/видалено/);
assert.equal(contents,beforeConflict);
console.log("PASS: persistence, snapshots, deduplication, preferences, removal, validation, unavailable storage, corrupt data preservation and limits.");
const regions=['Вінницька область','Чернівецька область','Хмельницька область','Тернопільська область'];
assert.deepEqual(saved.normalize({...filters,region:regions}).region,[...regions].sort());
assert.deepEqual(saved.normalize({...filters,region:[filters.region]}),saved.normalize(filters));
assert.equal(saved.normalize({...filters,region:[]}).region,'');
assert.deepEqual(saved.normalize({...filters,region:[...regions].reverse().concat(regions)}).region,[...regions].sort());
assert.throws(()=>saved.normalize({...filters,region:['']}));
assert.throws(()=>saved.normalize({...filters,region:[1]}));
contents=null;
const multi=saved.save(storage,{...filters,region:regions},'Чотири області',false);
assert.equal(saved.save(storage,{...filters,region:[...regions].reverse()},'Оновлена назва',false).id,multi.id);
assert.equal(saved.read(storage).length,1);
assert.deepEqual(saved.read(storage)[0].filters.region,[...regions].sort());
console.log('PASS: multi-region persistence, canonical order, legacy single-region compatibility and duplicate protection.');
