const assert=require("node:assert/strict");
const saved=require("./saved-searches.js");
let contents=null;
const storage={getItem:()=>contents,setItem:(key,value)=>{assert.equal(key,saved.KEY);contents=value;}};
const filters={brand:"BMW",model:"3 Series",region:"Київська область",price:{from:0,to:20000},year:{from:2018,to:null},mileage:{from:100,to:200},body:["Седан"],fuel:["Дизель","Бензин"],transmission:["Автомат"],onlyDeals:true};
assert.deepEqual(saved.read(storage),[]);
const item=saved.save(storage,filters,"BMW",true);
assert.equal(saved.read(storage)[0].notificationsWanted,true);
// Another read simulates reopening. Caller changes must not mutate snapshots.
filters.price.to=15000;
assert.equal(saved.read(storage)[0].filters.price.to,20000);
filters.price.to=20000;filters.fuel.reverse();
saved.save(storage,filters,"Новий підпис",false);
assert.equal(saved.read(storage).length,1);
assert.equal(saved.read(storage)[0].id,item.id);
assert.equal(saved.read(storage)[0].name,"Новий підпис");
saved.setWanted(storage,item.id,true);assert.equal(saved.read(storage)[0].notificationsWanted,true);
saved.remove(storage,item.id);assert.equal(saved.read(storage).length,0);
assert.throws(()=>saved.save(storage,{...filters,mileage:{from:200,to:100}},"bad",false));
assert.throws(()=>saved.save(storage,filters," ",false));
const quota={getItem:()=>null,setItem:()=>{throw Error("QuotaExceededError")}};
assert.throws(()=>saved.save(quota,filters,"BMW",true),/Quota/);
contents="{bad json";
assert.throws(()=>saved.save(storage,filters,"BMW",true));assert.equal(contents,"{bad json");
contents=JSON.stringify({version:99,searches:[]});
assert.throws(()=>saved.save(storage,filters,"BMW",true));assert.equal(JSON.parse(contents).version,99);
contents=null;
for(let i=0;i<20;i++)saved.save(storage,{...filters,price:{from:i,to:20000}},"Search "+i,false);
assert.throws(()=>saved.save(storage,{...filters,price:{from:21,to:20000}},"Extra",false),/20/);
assert.equal(saved.read(storage).length,20);
console.log("PASS: persistence, snapshots, deduplication, preferences, removal, validation, unavailable storage, corrupt data preservation and limits.");
